-- ============================================================================
-- VACANCIES SCHEMA MIGRATION
-- Creates tables: vacancies, applications, invitation_tokens, org_invitation_tokens
-- ============================================================================

-- ============================================================================
-- TABLE: vacancies
-- Job vacancies from HR specialists
-- ============================================================================
CREATE TABLE IF NOT EXISTS vacancies (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  created_by UUID REFERENCES hr_specialists(id) ON DELETE SET NULL,

  -- Basic information
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  requirements TEXT,
  location VARCHAR(255),
  employment_type VARCHAR(50) CHECK (employment_type IN ('full-time', 'part-time', 'contract', 'internship')),
  salary_min INTEGER,
  salary_max INTEGER,
  salary_currency VARCHAR(10) DEFAULT 'KZT',

  -- Ideal profile (generated by AI + manually edited)
  ideal_profile JSONB,

  -- Required skills (selected by HR manually)
  required_skills TEXT[],

  -- Status
  status VARCHAR(50) DEFAULT 'active' CHECK (status IN ('active', 'closed', 'archived')),

  -- Statistics
  candidates_count INTEGER DEFAULT 0,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_vacancies_org ON vacancies(organization_id);
CREATE INDEX IF NOT EXISTS idx_vacancies_created_by ON vacancies(created_by);
CREATE INDEX IF NOT EXISTS idx_vacancies_status ON vacancies(status);
CREATE INDEX IF NOT EXISTS idx_vacancies_employment_type ON vacancies(employment_type);

COMMENT ON TABLE vacancies IS 'Job vacancies posted by organizations';
COMMENT ON COLUMN vacancies.ideal_profile IS 'AI-generated and manually edited ideal candidate profile (JSON)';
COMMENT ON COLUMN vacancies.required_skills IS 'Array of canonical skill names from skills_dictionary';

-- ============================================================================
-- TABLE: invitation_tokens
-- Invitation tokens for candidates
-- ============================================================================
CREATE TABLE IF NOT EXISTS invitation_tokens (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  token VARCHAR(255) NOT NULL UNIQUE,
  hr_specialist_id UUID REFERENCES hr_specialists(id) ON DELETE CASCADE,
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  vacancy_ids UUID[],
  is_used BOOLEAN DEFAULT false,
  used_by UUID REFERENCES candidates(id) ON DELETE SET NULL,
  expires_at TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '30 days'),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_invitation_tokens_token ON invitation_tokens(token);
CREATE INDEX IF NOT EXISTS idx_invitation_tokens_hr ON invitation_tokens(hr_specialist_id);
CREATE INDEX IF NOT EXISTS idx_invitation_tokens_org ON invitation_tokens(organization_id);
CREATE INDEX IF NOT EXISTS idx_invitation_tokens_used ON invitation_tokens(is_used) WHERE is_used = false;
CREATE INDEX IF NOT EXISTS idx_invitation_tokens_expires ON invitation_tokens(expires_at) WHERE is_used = false;

COMMENT ON TABLE invitation_tokens IS 'Invitation tokens for candidates to register';
COMMENT ON COLUMN invitation_tokens.vacancy_ids IS 'Array of vacancy IDs this invitation is for';

-- ============================================================================
-- TABLE: org_invitation_tokens
-- Invitation tokens for HR to join organization
-- ============================================================================
CREATE TABLE IF NOT EXISTS org_invitation_tokens (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  token VARCHAR(255) NOT NULL UNIQUE,
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  invited_by UUID REFERENCES hr_specialists(id) ON DELETE SET NULL,
  email VARCHAR(255),
  is_used BOOLEAN DEFAULT false,
  used_by UUID REFERENCES hr_specialists(id) ON DELETE SET NULL,
  expires_at TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '7 days'),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_org_invitation_tokens_token ON org_invitation_tokens(token);
CREATE INDEX IF NOT EXISTS idx_org_invitation_tokens_org ON org_invitation_tokens(organization_id);
CREATE INDEX IF NOT EXISTS idx_org_invitation_tokens_email ON org_invitation_tokens(email);

COMMENT ON TABLE org_invitation_tokens IS 'Invitation tokens for HR specialists to join organization';

-- ============================================================================
-- TABLE: applications
-- Link between candidates and vacancies (applications)
-- ============================================================================
CREATE TABLE IF NOT EXISTS applications (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  candidate_id UUID NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  vacancy_id UUID REFERENCES vacancies(id) ON DELETE CASCADE,
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,

  -- Source of candidate
  source VARCHAR(50) NOT NULL CHECK (source IN ('invitation', 'talent_market')),
  invited_by UUID REFERENCES hr_specialists(id) ON DELETE SET NULL,
  acquired_by UUID REFERENCES hr_specialists(id) ON DELETE SET NULL,

  -- Status in vacancy pipeline
  status VARCHAR(50) DEFAULT 'invited' CHECK (status IN (
    'invited', 'registered', 'testing', 'tested', 'analyzed',
    'saved', 'interview', 'offer', 'hired', 'rejected'
  )),

  -- Compatibility score (calculated)
  compatibility_score INTEGER CHECK (compatibility_score >= 0 AND compatibility_score <= 100),

  -- Notes from HR
  notes TEXT,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE(candidate_id, vacancy_id)
);

CREATE INDEX IF NOT EXISTS idx_applications_candidate ON applications(candidate_id);
CREATE INDEX IF NOT EXISTS idx_applications_vacancy ON applications(vacancy_id);
CREATE INDEX IF NOT EXISTS idx_applications_org ON applications(organization_id);
CREATE INDEX IF NOT EXISTS idx_applications_status ON applications(status);
CREATE INDEX IF NOT EXISTS idx_applications_source ON applications(source);
CREATE INDEX IF NOT EXISTS idx_applications_score ON applications(compatibility_score);

COMMENT ON TABLE applications IS 'Applications (link between candidates and vacancies)';
COMMENT ON COLUMN applications.source IS 'How candidate was added: invitation or talent_market';
COMMENT ON COLUMN applications.compatibility_score IS 'AI-calculated compatibility score (0-100)';

-- ============================================================================
-- TRIGGERS: updated_at auto-update
-- ============================================================================
CREATE TRIGGER update_vacancies_updated_at
  BEFORE UPDATE ON vacancies
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_applications_updated_at
  BEFORE UPDATE ON applications
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- FUNCTION: Generate random invitation token
-- ============================================================================
CREATE OR REPLACE FUNCTION generate_invitation_token()
RETURNS VARCHAR AS $$
DECLARE
  characters TEXT := 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  result VARCHAR := '';
  i INTEGER;
BEGIN
  FOR i IN 1..32 LOOP
    result := result || substr(characters, floor(random() * length(characters) + 1)::int, 1);
  END LOOP;
  RETURN result;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION generate_invitation_token IS 'Generate random 32-character invitation token';
